apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-server-models-pvc
  namespace: book-worm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi
