apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: 'https://github.com/tranvutuan2001/book-worm'
    targetRevision: HEAD
    path: deployment/manifest/llm-server
  destination:
    server: https://kubernetes.default.svc
    namespace: book-worm
  ignoreDifferences:
    - group: "apps"
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName        # Set by k8s after binding — not in git
        - /spec/storageClassName   # May be defaulted/normalized by k8s
        - /spec/volumeMode        # Defaulted to Filesystem by k8s
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
